#!/bin/bash

# Check if an IP address is reachable using ping

# Check if an IP address is provided as an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Perform ping to the provided IP address
ping -c 5 "$1"
